default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: RealTimeVehicleTracking_development
  timeout: 5000


test:
  <<: *default
  database: RealTimeVehicleTracking_development_test
  timeout: 5000
